### ISSUE TITLE
승열씨에게..

### ISSUE THREAD

**Issue by khel-kim** [unsolvedproblem/unsolvedproblem.github.io#1]
안녕하세요 승열씨. 다름이 아니라 아침에 카톡을 보내지 말아달라고 하셔서, 깃허브 자체 '쪼기'(?)시스템 이슈를 작성해보아연.ㅋㅋㅋㅋㅋㅋ

라온피플 세번째 포스트 업로드 해주시구연, 라온피플 첫번째 포스트 오류 난거 수정해주세욘

**Comment by backgom2357** [comment]
올리구 수정 다했읍니다. 완료했으니 이 이슈는 닫아주세용
